### ISSUE TITLE
网站更新了老哥，应该是不行了

### ISSUE THREAD

**Issue by yh-wyz** [AxyLm/qna3ai-script#1]

**Comment by AxyLm** [comment]
上周加了google验证，现在好像又没了，可以再试试😂

**Comment by AxyLm** [comment]
本来打算研究下用selenium，现在看了不用了，又能继续用了
![image](https://github.com/AxyLm/qna3ai-script/assets/48370746/d498a845-6a56-483c-8bbf-4a48f53b6b01)
