### ISSUE TITLE
Abi question

### ISSUE THREAD

**Issue by vrumvrumich** [AxyLm/qna3ai-script#2]
https://github.com/AxyLm/qna3ai-script/blob/1c72766a2cba670f60bad7bc133c0a5899ca5780/src/scirpts/abi.ts#L3
Hello, I'm really interested how did you get this abi?

**Comment by AxyLm** [comment]
is opensource?

**Comment by AxyLm** [comment]
here
![image](https://github.com/AxyLm/qna3ai-script/assets/48370746/cac8dd3e-c7aa-403d-9846-c899e21a6129)

**Comment by vrumvrumich** [comment]
@AxyLm thank you, but why does frontend need this abi?

**Comment by AxyLm** [comment]
Yes, ABI is necessary for parsing methods and parameters when interacting with Solidity contracts on the frontend.

> @AxyLm谢谢，但是为什么前端需要这个abi？

**Comment by AxyLm** [comment]
> @AxyLm thank you, but why does frontend need this abi?

No problem! ABI is necessary for parsing methods and parameters when interacting with Solidity contracts on the frontend.

**Comment by vrumvrumich** [comment]
@AxyLm Thank you, i think it would be great to add ability to use proxy in your code i think it will cause minor changes

**Comment by vrumvrumich** [comment]
@AxyLm and why do you need this method https://github.com/AxyLm/qna3ai-script/blob/1c72766a2cba670f60bad7bc133c0a5899ca5780/src/scirpts/qna3ai.ts#L109?

**Comment by AxyLm** [comment]
> @AxyLm and why do you need this method
> 
> https://github.com/AxyLm/qna3ai-script/blob/1c72766a2cba670f60bad7bc133c0a5899ca5780/src/scirpts/qna3ai.ts#L109
> 
> ?


This method is designed to simulate the authentic login process and has not been utilized subsequently.
